version: '3'
services:
  postgres:
        image: postgres:10.5
        restart: always
        environment:
           - POSTGRES_USER=docent
           - POSTGRES_PASSWORD=university
           - POSTGRES_DB=departmentuniversity
        ports:
           - "5432:5432"
        volumes: 
          - ./docker/postgres-data:/var/lib/postgresql/data
          - ./docker/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  app:
        build: .
        environment:
           - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/departmentuniversity
        ports:
          - "8080:8080"
        depends_on:
          - postgres