version: '3'
services:
  postgres:
        image: postgres:10.5
        restart: always
        environment:
           - POSTGRES_USER=docent
           - POSTGRES_PASSWORD=university
           - POSTGRES_DB=departmentuniversity
        ports:
           - "5432:5432"
        volumes: 
          - ./docker/postgres-data:/var/lib/postgresql/data
          - ./docker/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  tomcat:
        depends_on:
          - postgres
        image: tomcat
        volumes:
           - ./target/DepartmentUniversity-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/DepartmentUniversity.war
           - ./docker/context.xml:/usr/local/tomcat/conf/Catalina/localhost/context.xml.default
        ports:
          - "8080:8080"        